version: '3'
services:
  postgres:
    image: ghcr.io/adoptingerlang/service_discovery/postgres:15.4
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: discovery
      POSTGRES_USER: discovery
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "discovery", "-d", "discovery"]
      interval: 1s
      timeout: 5s
      retries: 10

    volumes:
    - pgdata:/var/lib/postgresql/data

  flyway:
    image: ghcr.io/adoptingerlang/service_discovery/flyway:9.22
    command:
    - -url=jdbc:postgresql://postgres:5432/discovery
    - -user=discovery
    - -password=password
    - -connectRetries=60
    - migrate
    volumes:
    - ./apps/service_discovery_postgres/priv/migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
