apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-discovery-dev
nameSuffix: -dev
images:
- name: service_discovery
  newTag: main

configMapGenerator:
- envs:
  - dev.env
  name: configmap
resources:
- service_nodeport.yaml
- ../../base
- ../../postgres

replacements:
- source:
    version: v1
    kind: Service
    name: postgres
  targets:
  - select:
      kind: Deployment
      name: service-discovery
    fieldPaths:
    - spec.template.spec.containers.[name=service-discovery].env.[name=DB_HOST].value
  - select:
      kind: Job
      name: flyway
    fieldPaths:
    - spec.template.spec.containers.[name=flyway].env.[name=POSTGRES_SERVICE].value
  - select:
      kind: Deployment
      name: service-discovery
    fieldPaths:
    - spec.template.spec.initContainers.[name=flyway-validate].env.[name=POSTGRES_SERVICE].value
- source:
    version: v1
    kind: Deployment
    name: postgres
    fieldPath: spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_DB].value
  targets:
  - select:
      version: v1
      kind: Deployment
      name: service-discovery
    fieldPaths:
    - spec.template.spec.initContainers.[name=flyway-validate].env.[name=POSTGRES_DB].value
- source:
    version: v1
    kind: Deployment
    name: postgres
    fieldPath: spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_USER].value
  targets:
  - select:
      version: v1
      kind: Deployment
      name: service-discovery
    fieldPaths:
    - spec.template.spec.initContainers.[name=flyway-validate].env.[name=POSTGRES_USER].value
- source:
    version: v1
    kind: Deployment
    name: postgres
    fieldPath: spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_PASSWORD].value
  targets:
  - select:
      version: v1
      kind: Deployment
      name: service-discovery
    fieldPaths:
    - spec.template.spec.initContainers.[name=flyway-validate].env.[name=POSTGRES_PASSWORD].value
labels:
- includeSelectors: true
  pairs:
    overlay: dev
