apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: discovery
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: discovery
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:15.4
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      restartPolicy: Always
      volumes:
      - name: pgdata
        emptyDir: {}
        # TODO: add this back through a kustomize patch if we use it for stage/prod instead of cloudsql
        # persistentVolumeClaim:
        #   claimName: pgdata
