---
name: JUnit Report

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Download Test Report
      uses: dawidd6/action-download-artifact1@v6
      with:
        name: ct-test-results
        workflow: ${{ github.event.workflow.id }}
        run_id: ${{ github.event.workflow_run.id }}
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        commit: ${{github.event.workflow_run.head_sha}}
        report_paths: '**/_build/test/logs/*/junit_report.xml'
